### ISSUE TITLE
Please can I join this organisation?

### ISSUE THREAD

**Issue by CodingSpecies** [Jaidevstudio/support#1]
Is it possible for me to join this organisation? Thank you.

**Comment by VasudevJaiswal** [comment]
https://jdstudio.tk/pages/about.html

check the url for you are a become a maintainer

**Comment by CodingSpecies** [comment]
Thank you @VasudevJaiswal!  , but their is a spelling error in the word maintainer:

![image](https://user-images.githubusercontent.com/70807500/131995238-fe3656e7-ab02-499a-b9e6-db423f7321da.png)

**Comment by VasudevJaiswal** [comment]
Yes i will update it soon

**Comment by CodingSpecies** [comment]
Also, when I went to check the organisation members, I was still a member, not a maintainer, is it meant to be like that? 
As a maintainer, I can add websites for each repo, and make issue templates. Thanks.

**Comment by VasudevJaiswal** [comment]
Don't worry I update access for repo for you

**Comment by CodingSpecies** [comment]
Thank you

**Comment by VasudevJaiswal** [comment]
Now Your are the maintainer of the org

**Comment by CodingSpecies** [comment]
@VasudevJaiswal I don't know what's wrong, but it still shows I am a member? 
![image](https://user-images.githubusercontent.com/70807500/132034678-3aa1151e-b4d8-46ac-803d-73d04c98e36d.png)

thank you

**Comment by VasudevJaiswal** [comment]
You check any changes in repos not required any pull request

**Comment by CodingSpecies** [comment]
Is it this:
![image](https://user-images.githubusercontent.com/70807500/132037579-33ca0e91-645f-4531-a1a0-4e6e87202c92.png)

**Comment by VasudevJaiswal** [comment]
##Every repo you changes everything without any push pull and request ##
you are allowed to use all repo

**Comment by VasudevJaiswal** [comment]
Now you because a owner 
Add some members in org

**Comment by VasudevJaiswal** [comment]
Congratulations 👏

**Comment by CodingSpecies** [comment]
Thank you @VasudevJaiswal , I have added discussions and an issue template for others to join: 
![image](https://user-images.githubusercontent.com/70807500/132104930-67f6fb7a-c69e-4cf0-b2e2-d8c01a23cfcc.png)

**Comment by VasudevJaiswal** [comment]
That's great 😍

**Comment by VasudevJaiswal** [comment]
@CodingSpecies 
1. Plz do like eduhub bot acticon msg for auto msg for members

**Comment by VasudevJaiswal** [comment]
# like that #
![Screenshot (131)](https://user-images.githubusercontent.com/85981735/132135713-6af1ee0b-ed55-47b5-9889-e76c983d4836.png)

**Comment by VasudevJaiswal** [comment]
and tell how to do this

**Comment by CodingSpecies** [comment]
@VasudevJaiswal , I'll try to. Thanks.

**Comment by Garryharryfarry** [comment]
@CodingSpecies 
@CodingSpecies 
Plz invite me as a owner plz
I m VasudevJaiswal
