### ISSUE TITLE
Invite to org

### ISSUE THREAD

**Issue by Abhay0809** [Jaidevstudio/support#10]
## Why would you like to join the organisation?
As an open-source contributor, I love to help others and enhance my development skills, and also to get a proper pathway guide for my future career!

**Comment by VasudevJaiswal** [comment]
1. Check your email or 
2. [Click here](https://jdstudio.ti/) And Accept invitation

**Comment by VasudevJaiswal** [comment]
Check your email

**Comment by CodingSpecies** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by CodingSpecies** [comment]
You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by VasudevJaiswal** [comment]
1. Check your email or 
2. [Click here](https://github.com/jaidevstudio) And Accept invitation
