### ISSUE TITLE
Invite to org

### ISSUE THREAD

**Issue by akshitagupta15june** [Jaidevstudio/support#14]
## Why would you like to join the organisation?
To contribute to organisation

**Comment by VasudevJaiswal** [comment]
Check Your email OR vist this Page [Click Here](https://github.com/jaidevstudio)

**Comment by akshitagupta15june** [comment]
I didn't receive the invite

**Comment by akshitagupta15june** [comment]
@VasudevJaiswal

**Comment by VasudevJaiswal** [comment]
@akshitagupta15june 
Dear Member Plz Check again

**Comment by VasudevJaiswal** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by VasudevJaiswal** [comment]
#Dear Member
You show that you are part of this org, by making your org badge public. This will show our profile org on your profile to others:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)
