### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by brilliantseniordev** [Jaidevstudio/support#140]
### Name

brilliantseniordev

### Additional Context

I'd like to be a part of awesome community

**Comment by VasudevJaiswal** [comment]
# It's great having you contribute to this project
 If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our [Discord Server](https://discord.gg/wXFWgsAuzR) and our [GitHub Organisation](http://github.com/jaidevstudio) - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.

**Comment by VasudevJaiswal** [comment]
# You have generate duplicate new case
