### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by noobcodder23** [Jaidevstudio/support#158]
### Name

Ashu Sharma

### Discord Username (if applicable)

-

### Additional Context

Because I think I can  contribute in open project for skill development for my dev growth

**Comment by VasudevJaiswal** [comment]
# It's great having you contribute to this project
 If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our [Discord Server](https://discord.gg/wXFWgsAuzR) and our [GitHub Organisation](http://github.com/jaidevstudio) - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.

**Comment by VasudevJaiswal** [comment]
# It's great having you contribute to this project
 If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our [Discord Server](https://discord.gg/wXFWgsAuzR) and our [GitHub Organisation](http://github.com/jaidevstudio) - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.

**Comment by VasudevJaiswal** [comment]
## Please check your email or organisation page 🙏
