### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by web-demon** [Jaidevstudio/support#194]
### Name

Jose Long

### Discord Username (if applicable)

1084785679365586987

### Additional Context

Dear Organization Administrator!

I hope this message finds you well. I am writing to express my sincere interest in joining the "Jaidevstudio" organization on GitHub. After carefully reviewing your organization's projects and objectives, I am impressed by the high-quality work and collaborative spirit exhibited by your members.

Allow me to provide some relevant information about myself:

I have been actively involved in the design and development field for the past 10 years. Throughout my professional journey, I have gained extensive experience in web development, working on various projects. My background includes a solid understanding of technical stacks, enabling me to contribute effectively to design and development efforts.

I possess a diverse skill set, which I believe can contribute significantly to the ongoing and future projects undertaken by the "Jaidevstudio" organization.

I am particularly excited about the opportunity to collaborate with like-minded professionals in the "Jaidevstudio" organization. The chance to work alongside talented individuals, share knowledge, and collectively raise the bar in design and code excellence is genuinely inspiring to me. I am eager to contribute my skills and insights to the organization's projects, as well as learn from the collective expertise of its members.

I am confident that my dedication, strong work ethic, and collaborative mindset would make me a valuable asset to the "Jaidevstudio" organization. I am open to any selection or evaluation process you may have in place, and I am willing to provide any additional information or samples of my work that you may require.

Thank you for considering my application to join the "Jaidevstudio" organization. I look forward to the opportunity to contribute and learn from the talented individuals within the organization. Please feel free to reach out to me if you have any further questions or require additional information.

Best regards, Jose Long

**Comment by VasudevJaiswal** [comment]
# It's great having you contribute to this project
 If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our [Discord Server](https://discord.gg/wXFWgsAuzR) and our [GitHub Organisation](http://github.com/jaidevstudio) - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.

**Comment by VasudevJaiswal** [comment]
# Invitation sent for the GitHub Organisation. Welcome to the community 🎉#
 
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/jaidevstudio/people

## Like this
![image](https://user-images.githubusercontent.com/91027746/134157300-21905417-9d2e-44e9-9961-e38cd32ae457.png)

 ***
## Tips for practising:
 
 Remember contributing to open source is not just about code, its about collaboration, communication and adding value
 I hope that helps

**Comment by VasudevJaiswal** [comment]
## Please check your email or organisation page 🙏
