### ISSUE TITLE
Invite to org

### ISSUE THREAD

**Issue by aryashah2k** [Jaidevstudio/support#21]
## Why would you like to join the organisation?

Contribute | Collaborate | Innovate

**Comment by VasudevJaiswal** [comment]
Check your email or org page [Click here](https://github.com/jaidevstudio)

**Comment by CodingSpecies** [comment]
You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by VasudevJaiswal** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by aryashah2k** [comment]
Joined the Org and made the profile public!
