### ISSUE TITLE
Invite to org

### ISSUE THREAD

**Issue by Antonio-Riccelli** [Jaidevstudio/support#25]
## Name: 
Antonio

## Why would you like to join the organisation?
Would love to collaborate on open source projects!

**Comment by CodingSpecies** [comment]
You have received an email to join, or press this link - https://github.com/Jaidevstudio - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by CodingSpecies** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!
