### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by AmineAML** [Jaidevstudio/support#29]
### Name

Amine

### Discord Username (if applicable)

ZЭГK#3733

### Additional Context

Owner reached out to me to join

**Comment by CodingSpecies** [comment]
You have received an email to join, or press this link -https://github.com/Jaidevstudio - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by CodingSpecies** [comment]
If you need anything- *help* or *support* - please reopen this issue. Thank you.
