### ISSUE TITLE
Could I please join this organization

### ISSUE THREAD

**Issue by AvidCoder101** [Jaidevstudio/support#3]
I have contributed to this organization on the unique-github-profiles and I would like to become a member of this organization. Thanks (:

**Comment by VasudevJaiswal** [comment]
Now you become owner plz do something add members

**Comment by VasudevJaiswal** [comment]
Congratulations 🥳

**Comment by AvidCoder101** [comment]
@VasudevJaiswal Thanks, I can't seem to add members?

**Comment by VasudevJaiswal** [comment]
Now check

**Comment by AvidCoder101** [comment]
@VasudevJaiswal Thanks. Just to clarify, do I just invite anyone I know or do I invite only people to contribute to the org?

**Comment by AvidCoder101** [comment]
@VasudevJaiswal, just to clarify, do I only invite people who contribute to the org?

**Comment by VasudevJaiswal** [comment]
Don't just try
