### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by AbhinavXT** [Jaidevstudio/support#30]
### Name

Abhinav Pathak

### Discord Username (if applicable)

AbhinavPathak#9007

### Additional Context

I received the link

**Comment by CodingSpecies** [comment]
You have received an email to join, or press this link - https://github.com/Jaidevstudio- , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)
