### ISSUE TITLE
Say Hi

### ISSUE THREAD

**Issue by BaseMax** [Jaidevstudio/support#32]
### Name

Max Base

### Discord Username (if applicable)

BaseMax#3529

### Additional Context

https://github.com/BaseMax/

**Comment by CodingSpecies** [comment]
@BaseMax 
You have received an email to join, or press this link - https://github.com/JaidevStudio - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)


### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by VasudevJaiswal** [comment]
You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by VasudevJaiswal** [comment]
You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)
