### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Blastoise** [Jaidevstudio/support#34]
### Name

Ashutosh Kumar

### Discord Username (if applicable)

Ashutosh Kumar#9278

### Additional Context

I received email invitation.

**Comment by CodingSpecies** [comment]
You have received an email to join, or press this link - https://github.com/JaidevStudio - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)


### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by VasudevJaiswal** [comment]
If you need anything- *help* or *support* - please reopen this issue. Thank you.
