### ISSUE TITLE
Workflow constant errors

### ISSUE THREAD

**Issue by CodingSpecies** [Jaidevstudio/support#36]
### Description of the bug

Every time I seem to comment or do any activity, it always sends a notification, saying an error in .yml file.

### Project stack or language (e.g. front-end)

.yml files.

### Working Environment (e.g. operating system, browser, device)

browser, and when you push to local to remote.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/70807500/132959942-87bc448e-2798-41cd-8042-41175aa871d7.png)

### Add any other context about the problem here

@VasudevJaiswal.

**Comment by VasudevJaiswal** [comment]
@CodingSpecies
Ok i will see it

**Comment by CodingSpecies** [comment]
Thank you.

**Comment by sumitmukharjeeeeee** [comment]
> @CodingSpecies
> Ok i will see it

Error: Unable to resolve action `jaidevstudio/gh-action-community@main`, repository not found
this is the error I get while making any pr.

**Comment by CodingSpecies** [comment]
I get the repository not found and this whether I merge pr, issue or make anything:
![image](https://user-images.githubusercontent.com/70807500/133000975-f42de38f-7867-49f4-8ece-9a2d57d2dbaf.png)

**Comment by sumitmukharjeeeeee** [comment]
Maybe that yml file has some checks that are failing

**Comment by Panquesito7** [comment]
I made a [**pull request**](https://github.com/Jaidevstudio/support/pull/41) to fix this error. This should also get fixed in other repositories as well. If this is being used in other repositories, someone may want to create some good first issues for other people to get a green square. 🟩
