### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by CodingSpecies** [Jaidevstudio/support#43]
### What would you like to share?

Test issue to see if notifications stop

**Comment by CodingSpecies** [comment]
still receing notifications: 
![image](https://user-images.githubusercontent.com/70807500/133031397-1d7d9a56-6745-4e18-a6e7-e599180f7f3d.png)

**Comment by Garryharryfarry** [comment]
@CodingSpecies 
Plz invite me as a owner plz
I m VasudevJaiswal
