### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by iamrahulmahato** [Jaidevstudio/support#49]
### Name

Rahul Ranjan Mahato

### Discord Username (if applicable)

iamrahulmahato#0983

### Additional Context

I got to know about JD Studio by GitHub only by searching projects.

The things I like about the JD Studio community and the reason why I want to join the community because of the following reasons:

1) This community basically target the beginner who enters to open source which I like most
2) As a full-stack developer when I enter open source I face many problems and till now I am learning so the mistake I have 
    early I don't want others will repeat so if I join the community I can help them to don't repeat that mistake
3) As a student I am learning only and if I get to join the community I think I will learn more and grow

**Comment by VasudevJaiswal** [comment]
# It's great having you contribute to this project
 If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our [Discord Server](https://discord.gg/wXFWgsAuzR) and our [GitHub Organisation](http://github.com/jaidevstudio) - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.

**Comment by VasudevJaiswal** [comment]
# Invitation sent for the GitHub Organisation. Welcome to the community 🎉#
 
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/jaidevstudio/people

## Like this
![image](https://user-images.githubusercontent.com/91027746/134157300-21905417-9d2e-44e9-9961-e38cd32ae457.png)

 ***
## Tips for practising:
 
 Remember contributing to open source is not just about code, its about collaboration, communication and adding value
 I hope that helps

**Comment by VasudevJaiswal** [comment]
Please check your email or organisation page 🙏
