### ISSUE TITLE
Invite to org

### ISSUE THREAD

**Issue by mahatorakesh** [Jaidevstudio/support#6]
## Why would you like to join the organisation ?
hey, hope you doing great. i would like to join this organization as to enhanced my work experience in openSource project and work for community. Thank you.

**Comment by VasudevJaiswal** [comment]
Welcome 🤗
# check your email or organisation page

**Comment by CodingSpecies** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by CodingSpecies** [comment]
@mahatorakesh 
You can also show that you are part of this org, by making your org badge public. This will show our profile org on your profile when others see:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by mahatorakesh** [comment]
done
