### ISSUE TITLE
Invite to org

### ISSUE THREAD

**Issue by abhishekmorla** [Jaidevstudio/support#7]
## Why would you like to join the organization?

hey, hope you doing great. I would like to join this organization to enhance my work experience in the openSource project.
Thanks

**Comment by VasudevJaiswal** [comment]
CHECK YOUR EMAIL or visit this [Page](https://github.com/jaidevstudio)

**Comment by CodingSpecies** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

**Comment by CodingSpecies** [comment]
@abhishekmorla 

You show that you are part of this org, by making your org badge public. This will show our profile org on your profile to others:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by VasudevJaiswal** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by CodingSpecies** [comment]
I will close this issue for now, but if you have any questions, feel free to open this again, or open a new issue. Thanks.
