### ISSUE TITLE
Joining Org Request

### ISSUE THREAD

**Issue by Abhishek-kumar09** [Jaidevstudio/support#8]

**Comment by VasudevJaiswal** [comment]
Check Your Email or [click here](https://github.com/jaidevstudio)for connect the org

**Comment by CodingSpecies** [comment]
@Abhishek-kumar09 , when you go to the org's profile, you will see a banner, which is your invite.
You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

**Comment by VasudevJaiswal** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!
