### ISSUE TITLE
Please do not copy our communities strap line or screenshot our members 

### ISSUE THREAD

**Issue by eddiejaoude** [Jaidevstudio/support#9]
## This is the EddieHub Org and strap line...

<img width="913" alt="Screenshot 2021-09-06 at 01 24 46" src="https://user-images.githubusercontent.com/624760/132145614-31d067bb-9ac0-496a-9c58-00cc9403323f.png">

---

## You have completely copied, please remove

<img width="879" alt="Screenshot 2021-09-06 at 01 23 47" src="https://user-images.githubusercontent.com/624760/132145623-82d97205-320e-40b9-93c4-4350fa6311e0.png">

---

## Do not use screenshot of our members, use your own members

<img width="970" alt="Screenshot 2021-09-06 at 01 26 14" src="https://user-images.githubusercontent.com/624760/132145659-a6c7bf9c-897d-4c6c-99aa-57be4632ac71.png">

**Comment by VasudevJaiswal** [comment]
Sorry i will change it

**Comment by VasudevJaiswal** [comment]
# Now Ok #

![screencapture-github-Jaidevstudio-support-2021-09-06-06_55_34](https://user-images.githubusercontent.com/85981735/132148139-9356aee7-67e7-4b1c-9ac2-4454c6924842.png)

**Comment by VasudevJaiswal** [comment]
![Screenshot (141)](https://user-images.githubusercontent.com/85981735/132148192-aaf3d1aa-2496-4e88-bbcf-5a7524964148.png)
